# Generated by Django 2.0.2 on 2018-02-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180211_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='static/img/man.png', upload_to='static/img'),
        ),
    ]
