# Generated by Django 2.0.2 on 2018-02-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/static/img/man.png'),
        ),
    ]
